name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2EwZGZkNzQtZGJhNy00NTk5LTk5NzktMzdjMDIxMGI4OGQ2IiwidGVuYW50X2lkIjoiM2MyZjQyMzljMTQxZjJlZDBkNTBiZjlmOTAxZmQ2NzVjNjc1Nzg4ZGQyNDkyYTFiMmFjMDFiZWJiYTU2ZGQ0NCIsImludGVybmFsX3NlY3JldCI6IjNkMjA0ZDM4LTFjOTgtNGY4NS05NmEzLTJhYWQyOTg1ZTY2MiJ9.x-Y1Z8QT5kGjYAOm8wEhdUV-hWDwPAqKhNK_aZr7HWE"
SECRET="MY@secret@123$key*456"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"